# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SamplePOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SamplePOC

  target 'SamplePOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SamplePOCUITests' do
    # Pods for testing
  end

end
